name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http:
  splashscreen:
  flutter_svg: ^0.17.4
  firebase_core: ^0.4.4+3
  firebase_database:
  webview_flutter: ^0.3.20+2
  connectivity: ^0.4.8+2
  firebase_messaging:



  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - gif/
  - icons/

  fonts:
  - family: Digital-7
    fonts:
    - asset: fonts/digital-7.ttf
      weight: 900